# Generated by Django 3.2.19 on 2023-06-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_item_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='total',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
