# Generated by Django 3.2.19 on 2023-06-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_products_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
